name: 'Automated Tests'

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Code Lint
        run: make tools && make lint
      - name: Website
        run: make tools && make website-lint
      - name: Test
        env:
          MONGODB_ATLAS_TEAMS_IDS: ${{ secrets.MONGODB_ATLAS_TEAMS_IDS }}
          SKIP_TEST_EXTERNAL_CREDENTIALS: ${{ secrets.SKIP_TEST_EXTERNAL_CREDENTIALS }}
          SKIP_TEST_IMPORT: ${{ secrets.SKIP_TEST_IMPORT }}
          SKIP_TEST: ${{ secrets.SKIP_TEST }}
        run: make test
